---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: devenv
  template:
    metadata:
      labels:
        env: devenv
    spec:
      containers:
        - name: mycontainer
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sathya
              mountPath: /opt/reddy/

        - name: helpercontainer
          image: busybox
          command:
            - /bin/sh
            - -c
            - while true; do echo welcome to sathya; sleep 10; done
          volumeMounts:
            - name: sathya
              mountPath: /opt/reddy/
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "20Mi"
              cpu: "200m"

      volumes:
        - name: sathya
          persistentVolumeClaim:
            claimName: mypvc

