---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      env: devenv
  template:
    metadata:
      name: mytemplate
      labels:
        env: devenv
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/nadha/
              name: sathya

        - name: cont2
          image: shaikmustafa/dm
          command: ["/bin/bash", "-c", "while true; do echo welcome to devenv; sleep 10; done"]
          volumeMounts:
            - mountPath: /opt/nadha/
              name: sathya

      volumes:
        - name: sathya
          persistentVolumeClaim:
            claimName: pvc
