---
apiVersion: v1  
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: dev  
spec:
  hard:
    pods: "10"
    requests.cpu: "200m"
    requests.memory: "100Mi"
    limits.cpu: "400m"
    limits.memory: "200Mi"
