---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
  namespace: dev    
spec:
  serviceName: "firstservice"
  replicas: 3
  selector:
    matchLabels:
      app: mystatefulset
  template:
    metadata:
      labels:
        app: mystatefulset
    spec:
      containers:
      - name: mycontainer
        image: shaikmustafa/dm
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "5Mi"
            cpu: "50mi"
          limits:
            memory: "10Mi"
            cpu: "100m"
