---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset   
spec:
  replicas: 3
  selector:
    matchLabels:
      env: devenv
  template:
    metadata:
      labels:
        env: devenv
    spec:
      containers:
      - name: mycontainer
        image: shaikmustafa/dm
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "5Mi"
            cpu: "50mi"
          limits:
            memory: "10Mi"
            cpu: "100m"
