---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset   
spec:
  replicas: 4
  selector:
    matchLabels:
      env: devenv
  template:
    metadata:
      labels:
        env: devenv
    spec:
      containers:
      - name: mycontainer
        image: shaikmustafa/dm
        ports:
        - containerPort: 80
